#theme: jekyll-theme-leap-day
remote_theme: pmarsceill/just-the-docs

title: Donjons & Dragons - yann.me
description: Aides, astuces, campagnes, ressources Donjons & Dragons

logo: "/assets/dungeons-and-dragons-logo.png"

aux_links:
  "Retour au site yann.me":
    - "https://yann.me"

# Enable or disable the site search
search_enabled: true

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2023  Yann Jajkiewicz."

# Color scheme currently only supports "dark" or nil (default)
color_scheme: dark

# Archives
jekyll-archives:
  enabled: 'all'
  layout: archive
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
    
# jekyll plugins
plugins:
  - jekyll-sitemap
  - jekyll-archives
